openapi: 3.0.0
info:
  version: '1.0'
  title: "BikeManBooking OpenAPI 3.0"
  description: API per gestione delle prenotazioni per le manutenzioni della propria bicicletta.
  license:
    name: MIT
servers:
  - url: http://localhost:3000
    description: Localhost
paths:
  /storico:
    get:
      description: >-
        Ritorna tutte le prenotazioni
      summary: Ritorna la lista di tutte le prenotazioni
      responses:
        '200':
          description: 'Collezione di prenotazioni'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prenotazione'
    post:
      description: >-
        Elimina la prenotazione futura selezionata dall'utente
      summary: Elimina la prenotazione selezionata
      responses:
        '200':
          description: 'Eliminazione di una prenotazione'
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Prenotazione'
          
  /calendario:
    get:
      description: >-
        Mostra il calendario
      summary:  Mostra il calendario
      responses:
        '200':
          description: "Mostra calendario"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prenotazione'
    post:
      description: >-
        Crea una nuova prenotazione (solo per clienti)
      summary: Crea una nuova prenotazione
      responses:
        '201':
          description: 'Crea una nuova prenotazione'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prenotazione'
        '502':
          description: 'Prenotazione non effetutata: uno o più parametri non sono validi'
          
  /calendario/prenotazioni:
    get:
      description: >-
        Mostra le prenotazioni per giorno, settimana o mese in base alla selezione dell'utente
      summary: Mostra le prenotazioni per giorno, settimana o mese
      responses:
        '200':
          description: "Mostra calendario le prenotazioni per giorno, settimana o mese in base alla selezione dell'utente"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prenotazione'
  /profilo:
    get:
      description: >-
        Mostra le informazione di base del profilo, quali numero di telefono e email, indirizzo, ecc..
      summary: Mostra le informazione di base del profilo
      responses:
        '200':
          description: "Mostra le informazione di base del profilo, quali numero di telefono e email, indirizzo, ecc.."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'

  
  /users:
    get:
      description: >-
        Ritorna le informazioni del profilo in formato json
      summary: Ritorna le informazioni del profilo in formato json
      responses:
        '200':
          description: "Ritorna le informazioni del profilo in formato json"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'
    put:
      description: >-
        Aggiorna le informazioni del profilo
      summary: Aggiorna le informazioni del profilo
      responses:
        '201':
          description: "Aggiorna le informazioni del profilo"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'
    post:
      description: >-
        Inserisce nel db le informazioni di un nuovo profilo
      summary: Inserisce nel db le informazioni di un nuovo profilo
      responses:
        '201':
          description: 'Inserisce nel db le informazioni di un nuovo profilo'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'
    delete:
      description: >-
        Elimina il profilo
      summary: Elimina il profilo
      responses:
        '201':
          description: 'Elimina il profilo'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'
                  
  /auth:
    post:
      description: >-
        Gestisce la creazione di un nuovo account e il login
      summary: Gestisce l'autenticazione
      responses:
        '201':
          description: 'Gestisce la creazione di un nuovo account e/o il login'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'
  
components:
  schemas:
  
    Utente:
      type: object
      required: 
        - email
        - password
        - nome
        - cognome
        - bikes
        - ebikes
        - telefono
        - indirizzo
        - client
        - token
      properties:
        email:
          type: string
          example: "mario.rossi@gmail.com"
          description: "Indirizzo email dell'utente"
        password:
          type: string
          example: "Password1"
          description: "Password dell'utente"
        nome: 
          type: string
          example: "Mario"
          description: "Nome dell'utente"
        cognome: 
          type: string
          example: "Rossi"
          description: "Cognome dell'utente"
        bikes:
          type: array
          items:
            type: string
          example: ["colnago", "giant", "willier"]
          description: "Array contente le bici muscolari dell'utente"
        ebikes:
          type: array
          items:
            type: string
          example: ["cube", "scott"]
          description: "Array contente le bici elettriche dell'utente"
        telefono:
          type: string
          example: "333 1234567"
          description: "Numero di telefono dell'utente"
        indirizzo:
          type: string
          example: "Via Brigata Mantova, 41, 38061 Ala TN"
          description: "Indirizzo fisico dell'officina"
        client:
          type: boolean
          example: "true"
          description: "Attributo che indica se l'utente è un cliente o il proprietario dell'officina"
        token:
          type: string
          description: "Token usato per l'autenticazione"
        
    Prenotazione:
      type: object
      required:
        - data
        - utente
        - tipoProblema
        - bici
      properties:
        data:
          type: string # this include dates 
          example: "2022-05-26"
          description: 'Data della prenotazione'
        utente:
          type: string
          example: "mario.rossi@gmail.com"
          description: 'Utente che ha effettuato la prenotazione'
        tipoProblema:
          type: string
          example: "Regolazione sella"
          description: 'Descrizione del problema'
        bici:
          type: string
          example: "willier"
          description: 'Marca della bici che richiede la manutenzione'