GET  http://localhost:3000/users

###

POST http://localhost:3000/users

###

GET  http://localhost:3000/users/15

###

POST  http://localhost:3000/users
Content-Type: application/json

{
    "email": "bismirco@email.it",
    "password": "123"

}